$mpris_art = /tmp/hyde-mpris.png
$wall = ~/.config/hypr/hyprlock-assets/1.png
$hyprlockDir = $HOME/.config/hypr/hyprlock-assets
$music = $hyprlockDir/scripts/playerctlock.sh
$battery = $hyprlockDir/scripts/battery.sh
source = $hyprlockDir/colors.conf

background {
    monitor =
    path = $wall
}

general {
    no_fade_in = false
    disable_loading_bar = false
    grace = 1
    fail_timeout = 1000
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M %p")</span>"
    color = rgba(236, 239, 244, 1.0)
    font_size = 80
    position = -610, 250
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B %Y")"
    color = rgba(180, 180, 190, 0.75)
    font_size = 20
    text_align = left
    position = 180, 175
    halign = left
    valign = center
}

image {
    monitor =
    path = /home/byte/Pictures/Profile Pictures/83bc8b88cf6bc4b4e04d153a418cde62.jpg
    border_size = 2
    border_color = rgba(180, 180, 180, .75)
    size = 180
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd =
    position = -630, 10
    halign = center
    valign = center
}

shape {
    monitor =
    size = 320, 55
    color = rgba(50, 50, 50, 0.4)
    rounding = -1
    border_color = rgb(255, 255, 255)
    border_size = 2
    rotate = 0
    xray = false
    position = -630, -140
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgb(200, 200, 200)
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = -630, -140
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 55
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 1.0)
    inner_color = rgba(50, 50, 50, 0.4)
    font_color = rgb(240, 240, 240)
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = enter password...
    hide_input = false
    position = -630, -220
    halign = center
    valign = center

    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    swap_font_color = false
}

shape {
    monitor =
    size = 350, 110
    color = rgba(50, 50, 50, 0.4)
    rounding = 20
    rotate = 0
    border_size = 2
    border_color = rgba(255, 255, 255, 0.75)
    position = -630, -350
    halign = center
    valign = center
    zindex = 1
}

image {
    monitor =
    path = $mpris_art
    size = 86
    border_size = 3
    border_color = rgba(255, 255, 255, 0.8)
    rounding = 5
    rotate = 0
    reload_time = 0
    reload_cmd =
    position = 167, -350
    halign = left
    valign = center
    zindex = 5
}

label {
    monitor =
    text = cmd[update:1000] echo "$($music --artist)"
    color = rgb(200, 200, 200)
    font_size = 12
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 270, -375
    halign = left
    valign = center
    zindex = 5
}

label {
    monitor =
    text = cmd[update:1000] echo "$($music --title)"
    color = rgb(240, 240, 240)
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 270, -350
    halign = left
    valign = center
    zindex = 5
}

label {
    monitor =
    text = cmd[update:1000] echo "$($music --source)"
    color = rgb(150, 150, 150)
    font_size = 12
    font_family = JetBrains Mono Nerd Font Mono
    position = 270, -320
    halign = left
    valign = center
    zindex = 5
}

# BATTERY (bottom-right)
label {
    monitor =
    text = cmd[update:5000] $battery
    color = rgba(255, 255, 255, 0.85)
    font_size = 15
    font_family = JetBrains Mono Nerd Font
    position = -20, 20
    halign = right
    valign = bottom
    zindex = 20
}

