// Auto-generated by pywal
// Do not edit unless you wanna waste time

pragma Singleton

import Quickshell
import QtQuick

Singleton {
  readonly property bool isDark: true

  // Backgrounds
  readonly property color mainPanelBackground: "#000000"
  readonly property color itemBackground: "#000000"
  readonly property color itemHoveredBackground: "#aaaaaa"
  readonly property color itemPressedBackground: "#f4f4f4"
  readonly property color itemDisabledBackground: "#000000"

  // Text
  readonly property color text: "#f4f4f4"
  readonly property color bigText: "#f4f4f4"
  readonly property color smallText: "#aaaaaa"

  // Accents / separators
  readonly property color separator: "#000000"
  readonly property color itemWarningBackground: "#6F6F6F"

  readonly property int colorTransitionTime: 50
}
