# Shell variables
# Generated by 'wal'
wallpaper='/home/byte/Pictures/Wallpapers/static/a.jpg'

# Special
background='#000000'
foreground='#f4f4f4'
cursor='#f4f4f4'

# Colors
color0='#000000'
color1='#6F6F6F'
color2='#8F8F8F'
color3='#B0B0B0'
color4='#D0D0D0'
color5='#E8E8E8'
color6='#F3F3F3'
color7='#f4f4f4'
color8='#aaaaaa'
color9='#6F6F6F'
color10='#8F8F8F'
color11='#B0B0B0'
color12='#D0D0D0'
color13='#E8E8E8'
color14='#F3F3F3'
color15='#f4f4f4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
