foreground   #f4f4f4
background   #000000
cursor       #f4f4f4

color0       #000000
color8       #aaaaaa
color1       #6F6F6F
color9       #6F6F6F
color2       #8F8F8F
color10      #8F8F8F
color3       #B0B0B0
color11      #B0B0B0
color4       #D0D0D0
color12      #D0D0D0
color5       #E8E8E8
color13      #E8E8E8
color6       #F3F3F3
color14      #F3F3F3
color7       #f4f4f4
color15      #f4f4f4
