font_family JetBrainsMono Nerd Font
font_size 12.0

background_opacity 0.9
dynamic_background_opacity yes

foreground #f4f4f4
background #000000
cursor #f4f4f4
selection_foreground #000000
selection_background #D0D0D0

color0 #000000
color8 #aaaaaa

color1 #6F6F6F
color9 #6F6F6F

color2 #8F8F8F
color10 #8F8F8F

color3 #B0B0B0
color11 #B0B0B0

color4 #D0D0D0
color12 #D0D0D0

color5 #E8E8E8
color13 #E8E8E8

color6 #F3F3F3
color14 #F3F3F3

color7 #f4f4f4
color15 #f4f4f4

map ctrl+a kitten kitty_grab/grab.py

map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard

map kitty_mod+Left no_op
map kitty_mod+Right no_op

map ctrl+t new_tab
map ctrl+w close_tab
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9

enabled_layouts splits

map alt+i launch --location=hsplit
map alt+k launch --location=hsplit
map alt+j launch --location=vsplit
map alt+l launch --location=vsplit

map alt+q close_window

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down
