font_family JetBrainsMono Nerd Font
font_size 12.0

background_opacity 0.9
dynamic_background_opacity yes

foreground {foreground}
background {background}
cursor {cursor}
selection_foreground {background}
selection_background {color4}

color0 {color0}
color8 {color8}

color1 {color1}
color9 {color9}

color2 {color2}
color10 {color10}

color3 {color3}
color11 {color11}

color4 {color4}
color12 {color12}

color5 {color5}
color13 {color13}

color6 {color6}
color14 {color14}

color7 {color7}
color15 {color15}

map ctrl+a kitten kitty_grab/grab.py

map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard

map kitty_mod+Left no_op
map kitty_mod+Right no_op

map ctrl+t new_tab
map ctrl+w close_tab
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9

enabled_layouts splits

map alt+i launch --location=hsplit
map alt+k launch --location=hsplit
map alt+j launch --location=vsplit
map alt+l launch --location=vsplit

map alt+q close_window

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down
